--- isomaster-1.3/Makefile	2007-12-12 16:48:16.000000000 -0500
+++ Makefile	2008-01-01 22:15:32.000000000 -0500
@@ -1,5 +1,5 @@
 # Other paths are relative to this.
-PREFIX ?= /usr/local
+PREFIX ?= /usr
 
 # Where to install the executable.
 BINPATH ?= $(PREFIX)/bin
