#!/bin/sh

if [ $1 ];
then
    trove=$1
else
    trove="group-desktop-platform"
fi

branch=$(grep -m 1 ^branch CONARY)
case $branch in
  *:2-devel-kernel)
    BRANCH="foresight.rpath.org@fl:2-devel-kernel"
    MAP="foresight.rpath.org@fl:2-devel--foresight.rpath.org@fl:2-qa foresight.rpath.org@fl:2-devel-kernel--foresight.rpath.org@fl:2-qa-kernel"
    TARGET="fl:2-qa-kernel"
    ;; 
  */2-devel)
    BRANCH="foresight.rpath.org@fl:2-devel"
    MAP="foresight.rpath.org@fl:2-devel--foresight.rpath.org@fl:2-qa foresight.rpath.org@fl:2-devel-kernel--foresight.rpath.org@fl:2-qa-kernel"
    TARGET="fl:2-qa"
    ;;
  */2-qa)
    BRANCH="foresight.rpath.org@fl:2-qa"
    MAP="foresight.rpath.org@fl:2-qa--foresight.rpath.org@fl:2 foresight.rpath.org@fl:2-qa-kernel--foresight.rpath.org@fl:2-kernel"
    TARGET="fl:2"
    ;;
  */2)
    echo "DO NOT PROMOTE ON STABLE LABEL!"
    exit 1
    ;;
  *)
    echo $branch
    echo "WHERE ARE YOU?"
    exit 1
    ;;
esac

set -x
time cvc promote -m "Promote to $TARGET" \
  --all-flavors \
  --interactive \
  $trove=$BRANCH \
  $MAP \
  "$@"

if [ $? -eq 0 -a -x $HOME/bin/twitter ];
then
    $HOME/bin/twitter "$@ promoted to $TARGET"
fi
