<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.10.2 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 10420 2007-06-03 23:30:40Z lem9 $
 * Date: Thu, 05 Jul 2007 02:03:49 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (config:root) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */
?>
