#!/bin/bash
#
# Init file for NoIP2 dynamic dns updater
#
# chkconfig: 345 99 80
# description: Starts and stops the no-ip.com Dynamic dns client daemon
#
# pidfile: /var/run/noipd.pid
#

# Source function library.
. /etc/init.d/functions

# Avoid using root's TMPDIR
unset TMPDIR

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

RETVAL=0

start() {
    checkconfig || return 1
    if [ -f /var/run/noipd.pid ] ; then
	echo "no-ip client daemon already started" && exit 0
    fi
    echo -n $"Starting no-ip client daemon: "
    daemon /usr/bin/noip2 -c /etc/no-ip2.conf
    echo
    RETVAL=$?
    /sbin/pidof noip2 > /var/run/noipd.pid
}	

stop() {
    if [ -f /var/run/noipd.pid ] ; then
	echo -n $"Stopping no-ip client daemon: "
	killproc noip2 -TERM
	echo
	RETVAL=$?
	rm -f /var/run/noipd.pid
    else
	echo "no-ip client daemon is not running" && exit 0
    fi
    return $RETVAL
}	

restart() {
    stop
    start
}	

checkconfig() {
    if [ ! -f /etc/no-ip2.conf ]
    then
	echo "Answer the following questions about your no-ip account."
	noip2 -C || return 1
    fi
}

case "$1" in
    start)
  	start
	;;
    stop)
  	stop
	;;
    restart)
  	restart
	;;
    checkconfig)
	checkconfig
	;;
    *)
	echo $"Usage: $0 {start|stop|restart|checkconfig}"
	exit 1
esac

exit $?
