#!/bin/sh

# Allow users to override command-line options
# Based on Gentoo's chromium package (and by extension, Debian's)
if [[ -f /etc/chromium/default ]]; then
	. /etc/chromium/default
fi

# Prefer user defined CHROMIUM_USER_FLAGS (from env) over system
# default CHROMIUM_FLAGS (from /etc/chromium/default)
CHROMIUM_FLAGS=${CHROMIUM_USER_FLAGS:-$CHROMIUM_FLAGS}

export CHROME_WRAPPER=%(libdir)s/chromium-browser/chrome
export CHROME_DESKTOP=chromium-browser.desktop
exec %(libdir)s/chromium-browser/chrome $CHROMIUM_FLAGS "$@"

