#!/bin/sh
#
# Copyright (c) 2011 Foresight Linux
# This file is distributed under the terms of the MIT License.
# A copy is available at http://www.rpath.com/permanent/mit-license.html
#
# Dummy switchlib{GL,glx}

if [ "$(whoami)" != "root" ]; then
    echo "Must be root to run this script." 1>&2
    exit 1
fi

if [ $# -ge 2 ]; then
    echo "Usage: $(basename $0) <amd|intel|query>" 1>&2
    echo "Please choose one parameter" 1>&2
    exit 1
fi

case "$1" in
    amd)
        echo "Switch to AMD" 1>&2
    ;;
    intel)
        echo "Switch to Intel" 1>&2
    ;;
    query)
        echo "amd"
    ;;
    *)
        echo "Usage: $(basename $0) <amd|intel|query>" 1>&2
        exit 1
    ;;
esac

exit 0
