#!/bin/sh

prefix=%(prefix)s
exec_prefix=%(exec_prefix)s

usage="\
Usage: openal-config [--prefix]] [--exec-prefix] [--version] [--libs] [--cflags]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix)
      echo $prefix
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      pkg-config --modversion openal
      ;;
    --cflags)
      pkg-config --cflags openal
      ;;
    --libs)
      pkg-config --libs openal
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

exit 0
